<?php ob_start() ?><!DOCTYPE html><html lang="he" dir="rtl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0,viewport-fit=cover"><title><?= htmlspecialchars($pageTitle ?? 'LandingFlow') ?></title><meta name="description" content="<?= htmlspecialchars($pageDescription ?? '') ?>"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Frank+Ruhl+Libre:wght@700;900&family=Heebo:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@500;600;700&display=swap" rel="stylesheet"><style>
:root{--bg:#F7F6F3;--surface:#FFFFFF;--surface-2:#EFEDE8;--border:#E5E3DE;--ink:#16181C;--ink-soft:#5B5F66;--ink-faint:#9A9D9F;--primary:#16181C;--primary-2:#3B3B3B;--primary-dark:#000000;--signal:#1FAA6D;--signal-soft:#E4F5EC;--stamp:#A63A2E;--stamp-soft:#F3E4E1;--success:#16A34A;--warning:#F59E0B;--danger:#DC2626;--info:#0EA5E9;--radius-sm:8px;--radius-md:12px;--radius-lg:16px;--shadow-sm:0 1px 2px rgba(0,0,0,.04);--shadow-md:0 4px 16px rgba(0,0,0,.06);--shadow-lg:0 12px 40px rgba(0,0,0,.08);--container:1200px;--font-display:"Heebo","system-ui",-apple-system,sans-serif;--font-serif:"Frank Ruhl Libre",serif;--font-mono:"IBM Plex Mono",monospace}
*{margin:0;padding:0;box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:90px;overflow-x:hidden}body{font-family:var(--font-display);background:var(--bg);color:var(--ink);line-height:1.6;-webkit-font-smoothing:antialiased;overflow-x:hidden}a{color:inherit;text-decoration:none}ul{list-style:none}button{font-family:inherit;cursor:pointer;border:none;background:none}.container{max-width:var(--container);margin:0 auto;padding:0 24px}section{padding:80px 0}@media(min-width:760px){section{padding:120px 0}}
h1,h2{font-family:var(--font-serif)}
.live-badge{display:inline-flex;align-items:center;gap:7px;font-size:.78rem;font-weight:600;color:var(--signal);background:var(--signal-soft);padding:6px 12px;border-radius:100px}
.live-dot{width:7px;height:7px;border-radius:50%;background:var(--signal);flex-shrink:0;animation:livePulse 2s ease-in-out infinite}
@keyframes livePulse{0%,100%{opacity:1;box-shadow:0 0 0 0 rgba(31,170,109,.4)}50%{opacity:.85;box-shadow:0 0 0 5px rgba(31,170,109,0)}}
.icon-line{width:24px;height:24px;stroke:currentColor;fill:none;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round;flex-shrink:0}
.section-eyebrow{display:inline-flex;align-items:center;gap:8px;font-size:.72rem;font-weight:600;color:var(--ink-soft);background:var(--surface-2);padding:6px 14px;border-radius:100px;margin-bottom:16px;letter-spacing:.02em;text-transform:uppercase}
.section-title{font-size:clamp(1.8rem,4.5vw,2.8rem);font-weight:800;line-height:1.15;max-width:720px;margin-bottom:14px;letter-spacing:-.02em}
.section-sub{color:var(--ink-soft);font-size:1.05rem;max-width:560px;margin-bottom:48px;line-height:1.6}
.head-center{text-align:center;display:flex;flex-direction:column;align-items:center}
.btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;font-weight:600;font-size:.9rem;border-radius:8px;padding:12px 24px;transition:all .2s ease;white-space:nowrap;letter-spacing:-.01em}
.btn-primary{background:var(--primary);color:#fff}.btn-primary:hover{background:var(--primary-dark)}
.btn-secondary,.btn-ghost{background:var(--surface);color:var(--ink);border:1.5px solid var(--border)}.btn-secondary:hover,.btn-ghost:hover{border-color:var(--primary);background:var(--surface-2)}
.btn-lg{padding:16px 32px;font-size:1rem}.btn-sm{padding:8px 14px;font-size:.8rem}.btn-block{width:100%}
.btn:focus-visible{outline:2px solid var(--primary);outline-offset:2px}
.nav{position:fixed;top:0;right:0;left:0;z-index:500;height:70px;display:flex;align-items:center;background:rgba(250,250,250,.88);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);border-bottom:1px solid var(--border);transition:box-shadow .25s}
.nav.scrolled{box-shadow:0 1px 3px rgba(0,0,0,.04)}
.nav-inner{width:100%;max-width:var(--container);margin:0 auto;padding:0 24px;display:flex;align-items:center;justify-content:space-between}
.logo{display:flex;align-items:center;gap:8px;font-weight:800;font-size:1.08rem;letter-spacing:-.02em}.logo-mark{width:28px;height:28px;border-radius:7px;background:var(--primary);display:flex;align-items:center;justify-content:center;color:#fff;font-family:var(--font-mono);font-size:.78rem}
.nav-links{display:none;align-items:center;gap:32px;font-size:.86rem;font-weight:500;color:var(--ink-soft)}.nav-links a:hover{color:var(--ink)}.nav-actions{display:none;align-items:center;gap:8px}
.nav-icon-btn{width:36px;height:36px;border-radius:8px;display:flex;align-items:center;justify-content:center;color:var(--ink-soft);transition:all .2s}.nav-icon-btn:hover{background:var(--surface-2);color:var(--ink)}.nav-icon-btn.logout:hover{color:var(--danger)}
.burger{width:40px;height:40px;border-radius:8px;background:var(--surface);border:1px solid var(--border);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px}.burger span{width:18px;height:2px;background:var(--ink);border-radius:2px;transition:all .3s ease}.burger.active span:nth-child(1){transform:translateY(7px) rotate(45deg)}.burger.active span:nth-child(2){opacity:0}.burger.active span:nth-child(3){transform:translateY(-7px) rotate(-45deg)}
@media(min-width:1040px){.nav-links{display:flex}.nav-actions{display:flex}.burger{display:none}}
.mobile-menu{position:fixed;inset:0;z-index:600;visibility:hidden}.mobile-menu.open{visibility:visible}.menu-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.4);opacity:0;transition:opacity .3s}.mobile-menu.open .menu-backdrop{opacity:1}
.menu-panel{position:absolute;top:0;right:0;bottom:0;width:min(84vw,360px);background:var(--surface);box-shadow:-8px 0 30px rgba(0,0,0,.1);transform:translateX(100%);transition:transform .38s cubic-bezier(.22,1,.36,1);display:flex;flex-direction:column;padding:22px 22px 30px}.mobile-menu.open .menu-panel{transform:translateX(0)}
.menu-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:36px}.menu-close{width:38px;height:38px;border-radius:8px;background:var(--bg);font-size:1.1rem}
.mobile-links{display:flex;flex-direction:column;gap:6px;margin-bottom:auto}.mobile-links a{padding:14px 6px;font-size:1.05rem;font-weight:600;border-bottom:1px solid var(--border)}.menu-foot{display:flex;flex-direction:column;gap:10px;margin-top:24px}
.footer{background:var(--surface);padding-top:80px;margin-top:0;border-top:1px solid var(--border)}
.footer-grid{display:grid;grid-template-columns:1fr;gap:40px;padding-bottom:60px;border-bottom:1px solid var(--border)}@media(min-width:760px){.footer-grid{grid-template-columns:1.2fr 1fr 1fr}}@media(min-width:1050px){.footer-grid{grid-template-columns:1.2fr 1fr 1fr 1fr 1fr}}
.footer-brand p{color:var(--ink-soft);font-size:.88rem;max-width:280px;margin:16px 0 20px}.social-row{display:flex;gap:8px}.social-row a{width:36px;height:36px;border-radius:8px;background:var(--bg);border:1px solid var(--border);display:flex;align-items:center;justify-content:center;transition:.2s}.social-row a:hover{background:var(--primary);color:#fff}
.footer-col h4{font-size:.88rem;font-weight:700;margin-bottom:16px}.footer-col ul{display:flex;flex-direction:column;gap:10px}.footer-col a{color:var(--ink-soft);font-size:.86rem;transition:color .2s}.footer-col a:hover{color:var(--primary)}
.footer-bottom{display:flex;flex-direction:column;gap:14px;align-items:center;padding:26px 0;font-size:.82rem;color:var(--ink-faint)}@media(min-width:680px){.footer-bottom{flex-direction:row;justify-content:space-between}}.footer-legal{display:flex;gap:18px}
.form-group{margin-bottom:16px}.form-group label{display:block;font-size:.84rem;font-weight:600;margin-bottom:6px}.form-group input,.form-group textarea,.form-group select{width:100%;padding:12px 14px;border:1.5px solid var(--border);border-radius:8px;font-family:var(--font-display);font-size:.9rem;transition:border-color .2s}.form-group input:focus,.form-group textarea:focus,.form-group select:focus{outline:none;border-color:var(--primary)}
.check-row{display:flex;align-items:flex-start;gap:8px;font-size:.82rem;color:var(--ink-soft);margin-bottom:16px}.check-row input[type=checkbox]{width:auto;margin-top:3px;accent-color:var(--primary)}.check-row a{color:var(--primary);text-decoration:underline}
.pw-wrap{position:relative;display:flex;align-items:center}.pw-wrap input{padding-right:40px}.pw-toggle{position:absolute;right:10px;top:50%;transform:translateY(-50%);background:none;border:none;font-size:1.1rem;cursor:pointer;opacity:.5;transition:opacity .15s;padding:4px}.pw-toggle:hover{opacity:1}
.alert-success{background:rgba(22,163,74,.1);color:var(--success);border:1px solid rgba(22,163,74,.2);padding:10px 16px;border-radius:8px;margin-bottom:16px;font-size:.84rem}.alert-error{background:rgba(220,38,38,.08);color:var(--danger);border:1px solid rgba(220,38,38,.15);padding:10px 16px;border-radius:8px;margin-bottom:16px;font-size:.84rem}
.whatsapp-float{position:fixed;bottom:24px;left:24px;z-index:900;width:50px;height:50px;border-radius:12px;background:#25D366;color:#fff;display:flex;align-items:center;justify-content:center;font-size:1.3rem;box-shadow:0 4px 16px rgba(37,211,102,.2);transition:transform .25s}.whatsapp-float:hover{transform:scale(1.08)}
.whatsapp-tooltip{position:absolute;bottom:60px;left:0;background:#1f2937;color:#fff;padding:8px 14px;border-radius:8px;font-size:.82rem;white-space:nowrap;opacity:0;visibility:hidden;transform:translateY(4px);transition:opacity .2s,transform .2s}.whatsapp-tooltip.visible{opacity:1;visibility:visible;transform:translateY(0)}
/* Accessibility widget */
.a11y-float{position:fixed;bottom:88px;left:24px;z-index:900;width:50px;height:50px;border-radius:12px;background:var(--primary);color:#fff;display:flex;align-items:center;justify-content:center;font-size:1.4rem;box-shadow:0 4px 16px rgba(0,0,0,.15);transition:transform .25s;border:none;cursor:pointer}.a11y-float:hover{transform:scale(1.08)}
.a11y-panel{position:fixed;bottom:150px;left:24px;z-index:901;background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:16px;width:220px;box-shadow:0 8px 30px rgba(0,0,0,.12);display:none;flex-direction:column;gap:6px}.a11y-panel.open{display:flex}.a11y-panel h4{font-size:.85rem;font-weight:700;margin-bottom:6px;text-align:center}
.a11y-btn{width:100%;padding:9px 14px;font-size:.78rem;font-weight:600;border:1px solid var(--border);border-radius:8px;background:var(--bg);cursor:pointer;transition:all .15s;font-family:inherit;text-align:center}.a11y-btn:hover{background:var(--primary);color:#fff;border-color:var(--primary)}.a11y-reset{color:var(--danger);border-color:rgba(220,38,38,.2)}.a11y-reset:hover{background:var(--danger);color:#fff;border-color:var(--danger)}
body.high-contrast{filter:contrast(1.4) grayscale(.3)}body.large-text{font-size:115%}body.no-anim *,body.no-anim *::before,body.no-anim *::after{animation-duration:.001s!important;transition-duration:.001s!important}
a:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:2px solid var(--primary);outline-offset:2px;border-radius:4px}
@media(prefers-reduced-motion:reduce){*{animation-duration:.001s!important;transition-duration:.001s!important}html{scroll-behavior:auto}}
</style><script>function togglePw(btn){var inp=btn.parentElement.querySelector("input");var isPw=inp.type==="password";inp.type=isPw?"text":"password";btn.textContent=isPw?"🙈":"👁️"}</script></head><body>